# Generated by Django 3.1.2 on 2020-10-23 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sub_title',
            new_name='name',
        ),
    ]
